### ISSUE TITLE
Getting error when installing requirements, could not find yuicompressor 

### ISSUE THREAD

**Issue by petriichuk** [djaodjin/djaoapp#188]
ERROR: No matching distribution found for yuicompressor==2.4.8

**Comment by smirolo** [comment]
Apparently yuicompressor has disappeared from the Internet (at least as a pip package). Since we [replaced the webassets pipeline by a webpack pipeline](https://www.djaodjin.com/blog/django-building-static-assets.blog.html), those prerequisites were not used anymore so removing them was an easy fix. thanks.
